### ISSUE TITLE
Small issue

### ISSUE THREAD

**Issue by ghost** [ruian/RuianUploadifyBundle#2]
Hi! Thanks for the nice bundle!
I installed it on a project and noticed some small issue , decided to write it down:

In the Controller (in the documentation) you should have:

use Ruian\UploadifyBundle\Model\Ressource;
use Symfony\Component\HttpFoundation\Response; 

otherwise errors shows up.

Cheers!

**Comment by ruian** [comment]
Thx for noticing me :-)
