### ISSUE TITLE
Bad Autoload Path (composer)

### ISSUE THREAD

**Issue by umpirsky** [ruian/RuianUploadifyBundle#6]
In [composer.json](https://github.com/ruian/RuianUploadifyBundle/blob/master/composer.json#L8) there is a wrong path which after install with composer results in `vendor/.composer/autoload_namespaces.php` :

```
'Ruian' => $baseDir . '/vendor/ruian/uploadifybundle/../../',
```

instead:

```
 'Ruian' => $baseDir . '/vendor/ruian/uploadifybundle/',
```

And produces error:

```
Fatal error: Class 'Ruian\UploadifyBundle\RuianUploadifyBundle' not found
```

**Comment by umpirsky** [comment]
Suggested fix is to replace `"Ruian": "../../"` with `"Ruian": ""` in [composer.json](https://github.com/ruian/RuianUploadifyBundle/blob/master/composer.json#L8).

**Comment by ruian** [comment]
Thx for noticing. It's now fixed
